language: python
python::
<<<<<<< HEAD
 - "2.7"
 - "3.4"
 - "3.6.1"

install: pip install -r requirements.txt
script: 
  - pytest 
  - pytest --cov=./ coveralls
after_success: 
  - coveralls
=======
  - "2.7"
  - "3.4"
  - "3.6.1"
install: pip install -r requirements.txt
script: pytest 
after_success: coveralls
>>>>>>> ch-recreate-structure-158072403
